        'use strict';
        angular.module('app').controller('customerDetail',function($scope, productService, $http) {
            $scope.tabbar.setTabbarVisibility(true);
            $http.get(serverUrl + 'getdetailCustomerById?projectId=' + productService.CustomerId).success(
                function(data, status, headers, config) {
                    console.log( "implement date return from server ==="+data.ImplementDate);
                    
                    var convertedDate = new Date(data.ImplementDate.replace(' ', 'T'));
                    data.ImplementDate = new Date(convertedDate);
                    console.log( "implement date after format ==="+data.ImplementDate);
                    $scope.customerInfo = data;
                    $scope.customerPhoto=photoSever+"/attachments/projects/"+productService.CustomerId+".jpg";
                }).error(function(data, status, headers, config) {
                    console.log(data);      
                });
            $scope.changePhoto= function() {

            console.log(productService.CustomerId);
            var options = {
          quality: 45,
          targetWidth: 264,
          targetHeight: 264,
          destinationType: Camera.DestinationType.FILE_URI,
          encodingType: Camera.EncodingType.JPEG,
          sourceType: Camera.PictureSourceType.PHOTOLIBRARY
        };
        navigator.camera.getPicture(
          function(imageURI) {
            console.log(imageURI);
          //  upload(imageURI, customerId, userId,Detail);
              var imgProfile = document.getElementById('imgProject');

            // Show the captured photo
            // The inline CSS rules are used to resize the image
            //
            imgProfile.src = imageURI;
              
              
               var ft = new FileTransfer(),
        options = new FileUploadOptions();
        options.fileKey = "file";
        options.fileName = productService.CustomerId + ".jpg"; // We will use the name auto-generated by Node at the server side.
        options.mimeType = "image/jpeg";
        options.chunkedMode = false;
        options.params = { // Whatever you populate options.params with, will be available in req.body at the server-side.
          "description": "Uploaded from my phone",
          "customerId": productService.CustomerId
        };
                 ft.upload(imageURI, photoSever + "/service/updateProjectPhoto",
          function(e) {
          // upload photo
         console.log(JSON.parse(e.response));
        },
        function(e) {
          ons.notification.alert({
            message: 'Tải hình thất bại [5.2]'
          });
          spinnerplugin.hide();
        }, options);
              
              
              return false;
          },
          function(message) {
              // We typically get here because the use canceled the photo operation. Fail silently.
               return false;
            }, options);
          };

            });
